"use server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getAuthedUser } from "@/app/actions/bootcamp/auth";
import { normalizeQuestion, QUESTION_SELECT, type Question } from "@/lib/questions";

export type PracticeTest = { id: string; title: string; description: string | null; readingMinutes: number; mathMinutes: number; readingCount: number; mathCount: number; hasProgress: boolean };
export type PracticeTestPlayer = PracticeTest & { reading: Question[]; math: Question[]; answers: Record<string, string> };
export async function listPracticeTests(): Promise<PracticeTest[]> { const {user}=await getAuthedUser(); const admin=createAdminClient(); const {data,error}=await admin.from("tests").select("id,title,description,reading_minutes,math_minutes,test_questions(module)").order("created_at"); if(error)return []; const testIds=(data??[]).map(row=>String(row.id)); const {data:attempts}=user&&testIds.length?await admin.from("test_attempts").select("test_id").eq("user_id",user.id).in("test_id",testIds):{data:[]}; const started=new Set((attempts??[]).map(row=>String(row.test_id))); return (data??[]).map(row=>{const q=(row.test_questions??[]) as {module:string}[];return {id:String(row.id),title:String(row.title),description:row.description as string|null,readingMinutes:Number(row.reading_minutes),mathMinutes:Number(row.math_minutes),readingCount:q.filter(x=>x.module==="reading_writing").length,mathCount:q.filter(x=>x.module==="math").length,hasProgress:started.has(String(row.id))}}); }
export async function getPracticeTest(testId:string):Promise<PracticeTestPlayer|null>{const {user}=await getAuthedUser();if(!user)return null;const admin=createAdminClient();const {data:test,error}=await admin.from("tests").select("id,title,description,reading_minutes,math_minutes").eq("id",testId).maybeSingle();if(error||!test)return null;const {data:links}=await admin.from("test_questions").select("question_id,module,position").eq("test_id",testId).order("position");const ids=(links??[]).map(x=>String(x.question_id));const {data:rows}=ids.length?await admin.from("questions").select(QUESTION_SELECT).in("question_id",ids):{data:[]};const byId=new Map((rows??[]).map(x=>[String(x.question_id),normalizeQuestion(x as Record<string,unknown>)]));const reading:Question[]=[],math:Question[]=[];for(const link of links??[]){const q=byId.get(String(link.question_id));if(q)(link.module==="math"?math:reading).push(q)}const {data:attempts}=await admin.from("test_attempts").select("question_id,selected_answer").eq("test_id",testId).eq("user_id",user.id);return {id:String(test.id),title:String(test.title),description:test.description as string|null,readingMinutes:Number(test.reading_minutes),mathMinutes:Number(test.math_minutes),readingCount:reading.length,mathCount:math.length,hasProgress:(attempts??[]).length>0,reading,math,answers:Object.fromEntries((attempts??[]).filter(x=>x.selected_answer).map(x=>[String(x.question_id),String(x.selected_answer)]))};}
export async function savePracticeTestAnswer(params:{testId:string;questionId:string;selectedAnswer:string}){const {user}=await getAuthedUser();if(!user)throw new Error("Not signed in");const {error}=await createAdminClient().from("test_attempts").upsert({test_id:params.testId,user_id:user.id,question_id:params.questionId,selected_answer:params.selectedAnswer,updated_at:new Date().toISOString()});if(error)throw new Error("Could not save your answer");}
