"use client";
import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { savePracticeTestAnswer, type PracticeTestPlayer } from "@/app/actions";
import MathText from "@/components/MathText";

export default function PracticeTestPlayer({ test }: { test: PracticeTestPlayer }) {
  const router=useRouter(); const [module, setModule] = useState<"reading" | "math">("reading"); const [index,setIndex]=useState(0); const [answers,setAnswers]=useState(test.answers); const [seconds,setSeconds]=useState(test.readingMinutes*60); const [saving,setSaving]=useState(false); const [,start]=useTransition();
  const questions=module==="reading"?test.reading:test.math; const question=questions[index];
  useEffect(()=>{setIndex(0);setSeconds((module==="reading"?test.readingMinutes:test.mathMinutes)*60)},[module,test]);
  useEffect(()=>{const timer=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(timer)},[]);
  if(!question)return <p className="p-8">This module has no questions.</p>;
  const choose=(answer:string)=>{setAnswers(prev=>({...prev,[question.question_id]:answer}));start(()=>savePracticeTestAnswer({testId:test.id,questionId:question.question_id,selectedAnswer:answer}));};
  const saveAndExit=async()=>{setSaving(true);try{await Promise.all(Object.entries(answers).map(([questionId,selectedAnswer])=>savePracticeTestAnswer({testId:test.id,questionId,selectedAnswer})));router.push("/practice-tests");}finally{setSaving(false)}};
  const minutes=String(Math.floor(seconds/60)).padStart(2,"0"),secs=String(seconds%60).padStart(2,"0");
  return <div className="flex min-h-screen flex-col bg-white text-[#171717]"><header className="flex h-20 items-center justify-between border-b px-6"><button onClick={saveAndExit} disabled={saving} className="rounded-lg border px-4 py-2 text-sm font-medium disabled:opacity-60">{saving?"Saving…":"Save & exit"}</button><div className="text-center"><b>{test.title}</b><span className="ml-4 text-sm text-zinc-500">{module==="reading"?"Reading and Writing":"Math"}</span></div><b className="text-2xl tabular-nums">{minutes}:{secs}</b></header><main className="grid flex-1 lg:grid-cols-2"><section className="border-b p-8 lg:border-b-0 lg:border-r lg:p-14"><p className="mb-4 text-sm font-semibold text-zinc-500">Directions</p><div className="max-w-xl font-serif text-xl leading-relaxed"><MathText text={(question as unknown as { stimulus?: string }).stimulus || "Read the question carefully and choose the best answer."} /></div></section><section className="p-8 lg:p-14"><div className="mb-6 flex items-center justify-between"><span className="rounded-lg bg-black px-4 py-2 text-white">{index+1}</span><span className="text-sm text-zinc-500">Mark for review</span></div><div className="max-w-2xl"><div className="text-xl leading-relaxed"><MathText text={question.stem}/></div><div className="mt-7 space-y-3">{Object.entries(question.choices||{}).map(([key,value])=><button key={key} onClick={()=>choose(key)} className={`flex w-full items-center gap-4 rounded-2xl border-2 px-5 py-4 text-left text-lg transition ${answers[question.question_id]===key?"border-black bg-zinc-100":"border-zinc-300 hover:border-zinc-500"}`}><span className="grid h-9 w-9 place-items-center rounded-full border border-current text-sm">{key}</span><MathText text={value}/></button>)}</div></div></section></main><footer className="flex items-center justify-between border-t px-6 py-5"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)} className="rounded-xl border px-5 py-3 disabled:opacity-40">Previous</button><div className="flex gap-1">{questions.map((q,i)=><button key={q.question_id} onClick={()=>setIndex(i)} className={`h-8 w-8 rounded ${i===index?"bg-black text-white":answers[q.question_id]?"bg-cyan-100":"border"}`}>{i+1}</button>)}</div>{index===questions.length-1&&module==="reading"?<button onClick={()=>setModule("math")} className="rounded-xl bg-black px-5 py-3 text-white">Start Math</button>:<button disabled={index===questions.length-1} onClick={()=>setIndex(i=>i+1)} className="rounded-xl border px-5 py-3 disabled:opacity-40">Next</button>}</footer></div>;
}
